/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyect;

import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Adriana
 */

public class Menu extends javax.swing.JFrame {
    
    String ruta = "";
    File f = null;
    UndoManager manager = new UndoManager();
    /**
     * Creates new form Menu
     */
    public Menu() {
        manager = new UndoManager();
         initComponents();
         codigoText.getDocument().addUndoableEditListener(manager);
         setLocationRelativeTo(null);
       //setExtendedState(MAXIMIZED_BOTH);
       setVisible(true);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoArea = new javax.swing.JPanel();
        jLabelGuardado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codigoText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        errorBtn = new javax.swing.JButton();
        resBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoBtn = new javax.swing.JMenu();
        abrirBtn = new javax.swing.JMenuItem();
        guardarBtn = new javax.swing.JMenuItem();
        Gcomobtn = new javax.swing.JMenuItem();
        cerrar = new javax.swing.JCheckBoxMenuItem();
        editarBtn = new javax.swing.JMenu();
        copiar = new javax.swing.JMenuItem();
        Pegar = new javax.swing.JMenuItem();
        Cortar = new javax.swing.JMenuItem();
        Deshacer = new javax.swing.JMenuItem();
        formatoBtn = new javax.swing.JMenu();
        compilarBtn = new javax.swing.JMenu();
        ayudaBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoArea.setBackground(new java.awt.Color(204, 204, 255));
        codigoArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGuardado.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabelGuardado.setForeground(new java.awt.Color(0, 153, 0));
        codigoArea.add(jLabelGuardado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 250, -1));

        jScrollPane1.setBackground(new java.awt.Color(229, 229, 255));

        codigoText.setBackground(new java.awt.Color(244, 244, 255));
        codigoText.setColumns(20);
        codigoText.setRows(5);
        jScrollPane1.setViewportView(codigoText);

        codigoArea.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 450, 208));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Código a Compilar: ");
        codigoArea.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Lexico", jScrollPane4);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jTabbedPane1.addTab("Sintactico", jScrollPane5);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jTabbedPane1.addTab("Semantico", jScrollPane6);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        jTabbedPane1.addTab("Codigo Intermedio", jScrollPane7);

        codigoArea.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 340, 250));

        getContentPane().add(codigoArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 290));

        jPanel3.setBackground(new java.awt.Color(204, 204, 224));

        errorBtn.setBackground(new java.awt.Color(153, 153, 255));
        errorBtn.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        errorBtn.setText("Errores");
        errorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        errorBtn.setMargin(new java.awt.Insets(2, 14, 0, 14));
        errorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorBtnActionPerformed(evt);
            }
        });

        resBtn.setBackground(new java.awt.Color(153, 153, 255));
        resBtn.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        resBtn.setText("Resultados");
        resBtn.setBorderPainted(false);
        resBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resBtn.setMargin(new java.awt.Insets(2, 14, 0, 14));
        resBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resBtnMouseEntered(evt);
            }
        });
        resBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                resBtnMouseDragged(evt);
            }
        });
        resBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(244, 244, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setMargin(new java.awt.Insets(0, 2, 2, 2));
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(errorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 830, 170));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        archivoBtn.setText("Archivo");

        abrirBtn.setText("Abrir");
        abrirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirBtnMouseClicked(evt);
            }
        });
        abrirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirBtnActionPerformed(evt);
            }
        });
        archivoBtn.add(abrirBtn);

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });
        archivoBtn.add(guardarBtn);

        Gcomobtn.setText("Guardar como...");
        Gcomobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GcomobtnActionPerformed(evt);
            }
        });
        archivoBtn.add(Gcomobtn);

        cerrar.setSelected(true);
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        archivoBtn.add(cerrar);

        jMenuBar1.add(archivoBtn);

        editarBtn.setText("Editar");

        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        editarBtn.add(copiar);

        Pegar.setText("Pegar");
        Pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PegarActionPerformed(evt);
            }
        });
        editarBtn.add(Pegar);

        Cortar.setText("Cortar");
        Cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CortarActionPerformed(evt);
            }
        });
        editarBtn.add(Cortar);

        Deshacer.setText("Deshacer");
        Deshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeshacerActionPerformed(evt);
            }
        });
        editarBtn.add(Deshacer);

        jMenuBar1.add(editarBtn);

        formatoBtn.setText("Formato");
        jMenuBar1.add(formatoBtn);

        compilarBtn.setText("Compilar");
        jMenuBar1.add(compilarBtn);

        ayudaBtn.setText("Ayuda");
        jMenuBar1.add(ayudaBtn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void errorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorBtnActionPerformed

    private void resBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBtnActionPerformed
       
    }//GEN-LAST:event_resBtnActionPerformed

    private void resBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resBtnMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_resBtnMouseEntered

    private void abrirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_abrirBtnMouseClicked

    private void resBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resBtnMouseDragged
        // TODO add your handling code here:}
        
        
    }//GEN-LAST:event_resBtnMouseDragged

    private void abrirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirBtnActionPerformed
        // TODO add your handling code here:
       
        //Elegir archivo
        JFileChooser j = new JFileChooser();
        j.showOpenDialog(j);
        ruta = j.getSelectedFile().getAbsolutePath();
        //System.out.print(ruta);
        
        f = new File(ruta);
        Scanner entrada = null;
        String contenido = "";
        try {
            entrada = new Scanner(f);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Mostrar en pantalla
        while (entrada.hasNext()) { //mientras no se llegue al final del fichero
                contenido = contenido + entrada.nextLine() + "\n";  //se lee una líne
                
         }
        
        codigoText.setText(contenido);
 
    }//GEN-LAST:event_abrirBtnActionPerformed

    private void GcomobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GcomobtnActionPerformed
        // TODO add your handling code here:
        //GUARDAR COMO
        try {
            //String ruta = "/ruta/filename.txt";
            JFileChooser j = new JFileChooser();
            j.showOpenDialog(j);
            ruta = j.getSelectedFile().getAbsolutePath() + ".txt";
            
            String contenido = codigoText.getText().toString();
            f = new File(ruta);
            // Si el archivo no existe es creado
            if (!f.exists()) {
                f.createNewFile();
            }
            FileWriter fw = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(contenido);
            bw.close();
            
            jLabelGuardado.setText("Guardado");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GcomobtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        // TODO add your handling code here:
        
        //GUARDAR
        if(f!=null){
            System.out.println(f.getName());
            FileWriter fw = null;
            try {
                fw = new FileWriter(f);
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedWriter bw = new BufferedWriter(fw);
            
            try {
                bw.write(codigoText.getText().toString());
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                bw.close();
                jLabelGuardado.setText("Guardado");
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        codigoText.setText("");
    }//GEN-LAST:event_cerrarActionPerformed

    private void PegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PegarActionPerformed
        // TODO add your handling code here:
        codigoText.paste();
    }//GEN-LAST:event_PegarActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        // TODO add your handling code here:
        codigoText.copy();
    }//GEN-LAST:event_copiarActionPerformed

    private void CortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CortarActionPerformed
        // TODO add your handling code here:
        codigoText.cut();
    }//GEN-LAST:event_CortarActionPerformed

    private void DeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeshacerActionPerformed
        // TODO add your handling code here:
        manager.undo();
    }//GEN-LAST:event_DeshacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cortar;
    private javax.swing.JMenuItem Deshacer;
    private javax.swing.JMenuItem Gcomobtn;
    private javax.swing.JMenuItem Pegar;
    private javax.swing.JMenuItem abrirBtn;
    private javax.swing.JMenu archivoBtn;
    private javax.swing.JMenu ayudaBtn;
    private javax.swing.JCheckBoxMenuItem cerrar;
    private javax.swing.JPanel codigoArea;
    private javax.swing.JTextArea codigoText;
    private javax.swing.JMenu compilarBtn;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenu editarBtn;
    private javax.swing.JButton errorBtn;
    private javax.swing.JMenu formatoBtn;
    private javax.swing.JMenuItem guardarBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGuardado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JButton resBtn;
    // End of variables declaration//GEN-END:variables
}
